In [870]:
!pip install pandas


In [871]:
import pandas as pd


In [872]:
df = pd.read_csv("Used_Bikes.csv")

In [873]:
df.info

<bound method DataFrame.info of                                   bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

       

In [874]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [875]:
df.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [876]:
df.tail()

bike_name    price    city  kms_driven        owner  \
32643     Hero Passion Pro 100cc  39000.0   Delhi     22000.0  First Owner   
32644       TVS Apache RTR 180cc  30000.0  Karnal      6639.0  First Owner   
32645   Bajaj Avenger Street 220  60000.0   Delhi     20373.0  First Owner   
32646  Hero Super Splendor 125cc  15600.0  Jaipur     84186.0  First Owner   
32647         Bajaj Pulsar 150cc  22000.0    Pune     60857.0  First Owner   

        age  power  brand  
32643   4.0  100.0   Hero  
32644   9.0  180.0    TVS  
32645   6.0  220.0  Bajaj  
32646  16.0  125.0   Hero  
32647  13.0  150.0  Bajaj

In [877]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [878]:
df.describe()

price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [879]:
df.isnull()

bike_name  price   city  kms_driven  owner    age  power  brand
0          False  False  False       False  False  False  False  False
1          False  False  False       False  False  False  False  False
2          False  False  False       False  False  False  False  False
3          False  False  False       False  False  False  False  False
4          False  False  False       False  False  False  False  False
...          ...    ...    ...         ...    ...    ...    ...    ...
32643      False  False  False       False  False  False  False  False
32644      False  False  False       False  False  False  False  False
32645      False  False  False       False  False  False  False  False
32646      False  False  False       False  False  False  False  False
32647      False  False  False       False  False  False  False  False

[32648 rows x 8 columns]

In [880]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [881]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [882]:
df.duplicated().sum()

np.int64(25324)

In [883]:
df.drop_duplicates(inplace=True)

In [884]:
df.duplicated().sum()

np.int64(0)

In [885]:
df['brand']

0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...       
9362               Hero
9369              Bajaj
9370    Harley-Davidson
9371              Bajaj
9372              Bajaj
Name: brand, Length: 7324, dtype: object

In [886]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [887]:
df['brand'].nunique()

23

In [888]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [889]:
df.drop_duplicates(inplace=True)

In [890]:
df.duplicated().sum()

np.int64(0)

In [891]:
#df

In [892]:
#df['brand'].value_counts()

In [893]:
#df =df.drop(['city','bike_name'], axis=1 )

In [894]:
#df 

In [895]:
#cat_col =df.select_dtypes(include='object')

In [896]:
#cat_col

In [897]:
#num_cal=df.select_dtypes(exclude='object')

In [898]:
#num_cal

In [899]:
### bike brand = tvs
### kms = 50000
### price = 50000

#tvs_df=df[df['brand'] == 'TVS']

In [900]:
#tvs_df[tvs_df['kms_driven'] == 50000]

In [901]:
# brand == Royal Enfield
# price = 100000
# kms = 30000
# owner = first owner

# # bike availabality

In [902]:
# roy_df=df[df['brand'] == 'Royal Enfield']
# roy_df=roy_df[roy_df['kms_driven'] == 30000]
# roy_df=roy_df[roy_df['owner'] == 'First Owner']
# roy_df=roy_df[roy_df['price'] <= 100000]
# roy_df


In [903]:
#roy_df=df[(df['brand'] == 'Royal Enfield')&(df['kms_driven'] == 30000)&(df['owner'] == 'First Owner')&(df['price'] <= 100000)]

In [904]:
#roy_df

In [905]:
#df.query('brand == "Royal Enfield" and kms_driven == 30000 and owner == "First Owner" and price <= 100000')

In [906]:
#df.query('brand == "Hero" and age >= 2 and owner == "Second Owner" and price <= 50000')


In [907]:
# hero_df = df[
#     (df['brand'] == 'Hero') &
#     (df['price'] <= 50000) &
#     (df['owner'] == 'Second owner') &
#     (df['age'] >= 2)
# ]

In [908]:
#hero_df

In [909]:
#df

In [910]:
#df['owner'].unique()

In [911]:
owner_dict={'First Owner':1, 'Second Owner':2, 'Third Owner':3,
       'Fourth Owner Or More:':4}

In [912]:
owner_dict

{'First Owner': 1,
 'Second Owner': 2,
 'Third Owner': 3,
 'Fourth Owner Or More:': 4}

In [913]:
df['owner']=df['owner'].map(owner_dict)

In [914]:
df

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

      owner  age  power            brand  
0       1.0  3.0  110.0              TVS  
1       1.0  4.0  350.0    Royal Enfield  
2       1.0  8.0  675.0          Triumph  
3       1.0  4.0  180.0              TVS  
4       1.0  3.0  150.0           Yamaha  
...     ...  ...    ...              ...  
9362    1.0  8.0  150.0             Hero  
9369    1.0  9.0  220.0            Bajaj  
9370    1.0  4.0  750.0  Harley-Davidson  
9371    1.0  4.0  400.0            Bajaj  
9372    1.0  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [915]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [916]:
brand_dict = {
    'TVS':0, 'Royal Enfield':1, 'Triumph':2, 'Yamaha':3, 'Honda':4, 'Hero':5,
       'Bajaj':6, 'Suzuki':7, 'Benelli':8, 'KTM':9, 'Mahindra':10, 'Kawasaki':11,
       'Ducati':12, 'Hyosung':13, 'Harley-Davidson':14, 'Jawa':15, 'BMW':16, 'Indian':17,
       'Rajdoot':18, 'LML':19, 'Yezdi':20, 'MV':21, 'Ideal':22
}

In [917]:
df['brand']=df['brand'].map(brand_dict)

In [918]:
df

bike_name     price       city  kms_driven  \
0       TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1              Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0      Delhi       110.0   
3                     TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                    ...       ...        ...         ...   
9362             Hero Hunk Rear Disc 150cc   25000.0      Delhi     48587.0   
9369                   Bajaj Avenger 220cc   35000.0  Bangalore     60000.0   
9370        Harley-Davidson Street 750 ABS  450000.0    Jodhpur      3430.0   
9371                 Bajaj Dominar 400 ABS  139000.0  Hyderabad     21300.0   
9372              Bajaj Avenger Street 220   80000.0  Hyderabad      7127.0   

      owner  age  power  brand  
0       1.0  3.0  110.0      0  
1       1.0  4.0  350.0      1  
2       1.0  8.0  675.0      2  
3       1.0  4.0  180.0      0  
4       1.0  3.0  150.0      3  
...     ...  ...    ...    ...  
9362    1.0  8.0  150.0      5  
9369    1.0  9.0  220.0      6  
9370    1.0  4.0  750.0     14  
9371    1.0  4.0  400.0      6  
9372    1.0  5.0  220.0      6  

[7324 rows x 8 columns]

In [919]:
#df.corr()

In [920]:
df =df.drop(['city','bike_name'], axis=1 )

In [ ]:
df.isnull().sum()

price          0
kms_driven     0
owner         10
age            0
power          0
brand          0
dtype: int64

In [923]:
df = df.dropna(subset=['owner'])

In [924]:
x =df.drop('price',axis=1)
y =df[['price']]

In [925]:
x.isnull().sum()


kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [926]:
y

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7314 rows x 1 columns]

In [927]:
# model training step
# data spliting --------> test or training
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [928]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5851, 5), (1463, 5), (5851, 1), (1463, 1))

In [929]:
x_train

kms_driven  owner   age  power  brand
7752     38943.0    1.0   6.0  220.0      6
7997      1300.0    1.0   5.0  750.0     14
6218      8687.0    1.0   5.0  125.0      4
4498     14000.0    1.0   5.0  220.0      6
4960     55000.0    1.0  16.0  110.0     19
...          ...    ...   ...    ...    ...
7319      6500.0    1.0   6.0  150.0      7
6678     19255.0    1.0   7.0  150.0      6
7960      6859.0    1.0   3.0  200.0      9
6929     31477.0    1.0  11.0  150.0      6
1044      7400.0    1.0   3.0  125.0      4

[5851 rows x 5 columns]

In [930]:
# model traning step
from sklearn.linear_model import LinearRegression
model=LinearRegression()


In [931]:
model.fit(x_train, y_train)

LinearRegression()

In [932]:
print("training score:-",model.score(x_train,y_train))

training score:- 0.7091173622699839


In [933]:
print("testing score:-",model.score(x_test,y_test))

testing score:- 0.755127427175635


In [934]:
pred=model.predict(x_test)

In [935]:
pred = pred.ravel()

In [936]:
import numpy as np

In [937]:
y_test=np.array(y_test).ravel()

In [938]:
history = pd.DataFrame()

In [939]:
history

Empty DataFrame
Columns: []
Index: []

In [940]:
import joblib
joblib.dump(model,'linear_regression_model')

['linear_regression_model']

In [941]:
model = joblib.load('linear_regression_model')

In [942]:
#model.predict(x_test)

In [943]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [944]:
x,y = load_breast_cancer(return_X_y=True)

In [945]:
x #undependend 

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [946]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [947]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [948]:
logistic_model = LogisticRegression(max_iter=10000,random_state=0)

In [949]:
logistic_model.fit(x_train,y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [950]:
logistic_model.score(x_train,y_train)

0.9604395604395605

In [951]:
logistic_model.score(x_test,y_test)

0.956140350877193

In [952]:
pred = logistic_model.predict(x_test)

In [953]:
pred

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1])

In [954]:
y_test

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1])

In [955]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, SVR

In [956]:
x,y = load_iris(return_X_y=True)

In [957]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [958]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((120, 4), (120,), (30, 4), (30,))

In [959]:
svm_model=SVC(kernel='rbf',gamma=0.5,C=1.0) # high = overfit,low = underfit (0.01),gamma is used to single output,kernel is used to non linear data

In [960]:
svm_model.fit(x_train
              ,y_train)

SVC(gamma=0.5)

In [961]:
svm_model.score(x_train,y_train)

0.975

In [962]:
svm_model.score(x_test,y_test)

0.9666666666666667

In [963]:
pred = svm_model.predict(x_test)

In [964]:
pred

array([2, 2, 0, 1, 0, 1, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0,
       1, 0, 1, 1, 2, 1, 2, 1])

In [965]:
y_test

array([2, 2, 0, 1, 0, 1, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 0, 2, 2, 2, 1, 0,
       1, 0, 1, 1, 1, 1, 2, 1])